inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'daru.gemspec'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - '**/*.erb'
    - '**/*.csv'
    - 'spec/fixtures/**/*'
    # Remove one-by-one when specs are updated
    - spec/accessors/array_wrapper_spec.rb
    - spec/accessors/gsl_wrapper_spec.rb
    - spec/accessors/nmatrix_wrapper_spec.rb
    - spec/category_spec.rb
    - spec/core/group_by_spec.rb
    - spec/core/merge_spec.rb
    - spec/core/query_spec.rb
    - spec/daru_spec.rb
    - spec/dataframe_spec.rb
    - spec/date_time/data_spec.rb
    - spec/date_time/index_spec.rb
    - spec/date_time/offsets_spec.rb
    - spec/extensions/rserve_spec.rb
    - spec/extensions/which_dsl_spec.rb
    - spec/formatters/table_formatter_spec.rb
    - spec/helpers_spec.rb
    - spec/index/categorical_index_spec.rb
    - spec/index/multi_index_spec.rb
    - spec/io/io_spec.rb
    - spec/io/sql_data_source_spec.rb
    - spec/iruby/dataframe_spec.rb
    - spec/iruby/helpers_spec.rb
    - spec/iruby/multi_index_spec.rb
    - spec/iruby/vector_spec.rb
    - spec/maths/arithmetic/dataframe_spec.rb
    - spec/maths/arithmetic/vector_spec.rb
    - spec/maths/statistics/dataframe_spec.rb
    - spec/maths/statistics/vector_spec.rb
    - spec/monkeys_spec.rb
    - spec/plotting/gruff/category_spec.rb
    - spec/plotting/gruff/dataframe_spec.rb
    - spec/plotting/gruff/vector_spec.rb
    - spec/plotting/nyaplot/category_spec.rb
    - spec/plotting/nyaplot/dataframe_spec.rb
    - spec/plotting/nyaplot/vector_spec.rb
    - spec/shared/vector_display_spec.rb
    - spec/spec_helper.rb
    - spec/support/database_helper.rb
    - spec/support/matchers.rb
    - spec/vector_spec.rb
    - 'vendor/**/*'
    - 'benchmarks/*'
    - 'profile/*'
    - 'tmp/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.0

# Preferred codebase style ---------------------------------------------
Layout/ExtraSpacing:
  AllowForAlignment: true

Style/FormatString:
  EnforcedStyle: percent

Style/AndOr:
  EnforcedStyle: conditionals

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/EmptyElse:
  EnforcedStyle: empty

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 300

Style/ParallelAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

# See https://github.com/bbatsov/rubocop/issues/4429
Style/YodaCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'

# Neither of prefered styles are good enough :(
Style/BlockDelimiters:
  Enabled: false

RSpec/EmptyExampleGroup:
  CustomIncludeMethods: [its_call, its_map]

RSpec/NestedGroups:
  Enabled: false

# Current preferred metrics --------------------------------------------
# Better values are encouraged, but not required.
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# TODO -----------------------------------------------------------------

Style/Documentation:
  Enabled: false

RSpec/FilePath:
  Enabled: false

# To discuss and decide ------------------------------------------------

# FIXME: in fact, rescue modifier is rarely a good choice.
#  But currently I can't fully grasp the three places they are used.
#  So, leaving them intact. - zverok, 2016-05-07
Style/RescueModifier:
  Exclude:
    - 'lib/daru/accessors/gsl_wrapper.rb'
    - 'lib/daru/dataframe.rb'
    - 'lib/daru/io/sql_data_source.rb'

# FIXME: once we should enable and fix it - zverok, 2016-05-07
Style/Alias:
  Enabled: false

# Should be fixed, but require change of public API --------------------

# Bans methods like `has_missing_data?`, `is_number?` and so on - started
# with unnecessary has_ or is_.
Naming/PredicateName:
  Exclude:
    - 'lib/daru/dataframe.rb'
    - 'lib/daru/monkeys.rb'
    - 'lib/daru/vector.rb'

Security/MarshalLoad:
  Enabled: false
