inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'benchmarks/*'
  DisplayCopNames: true

Style/ExtraSpacing:
  AllowForAlignment: true

Style/FormatString:
  EnforcedStyle: percent

Style/AndOr:
  EnforcedStyle: conditionals
